trigger:
- main

variables:
  # Azure Resources
  azureSubscription: '8ce37efe-06df-47c4-b146-001d3ddfb1ba'
  resourceGroup: 'Project-Freshers_Park_Resource'
  containerRegistry: 'Project-Freshers-Park-App.azurecr.io'
  containerAppName: 'django-app'
  containerAppEnv: 'Project-Freshers-Park-App'
  composeFilePath: '**/docker-compose.yml'
  AZURE_KEY_VAULT_NAME: 'Freshers-Park-Keys'
  
  # Application Settings (non-secrets)
  DJANGO_SETTINGS_MODULE: 'job_portal.settings.production'
  DB_HOST: 'postgres'
  DB_PORT: '5432'
  DEBUG: 'False'
  ALLOWED_HOSTS: 'project-freshers-park-app-ezfqg6ezhyhvbzbx.centralindia-01.azurewebsites.net'
  PGADMIN_DEFAULT_EMAIL: 'akhiiltkaniiparampiil@gmail.com'

stages:
- stage: Build
  displayName: Build and push images
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Configure Key Vault Access'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Get current service principal details
          spId=$(az account show --query user.name -o tsv)
          
          if [ -z "$spId" ]; then
            echo "##vso[task.logissue type=error]Could not determine service principal ID"
            exit 1
          fi

          # Set Key Vault policy
          az keyvault set-policy \
            --name $(AZURE_KEY_VAULT_NAME) \
            --resource-group $(resourceGroup) \
            --object-id $spId \
            --secret-permissions get list

          # Verify policy was set
          az keyvault show --name $(AZURE_KEY_VAULT_NAME) \
            --query "properties.accessPolicies[?objectId == '$spId'].permissions.secrets" \
            -o table

    - task: AzureKeyVault@1
      displayName: 'Get secrets from Key Vault'
      inputs:
        azureSubscription: $(azureSubscription)
        KeyVaultName: $(AZURE_KEY_VAULT_NAME)
        SecretsFilter: '*'
        RunAsPreJob: true

    - task: DockerCompose@0
      displayName: 'Build services'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: $(composeFilePath)
        action: 'Build services'
        additionalImageTags: '$(Build.BuildId)'
        dockerComposeFileArgs: |
          DB_NAME=$(DB-NAME)
          DB_USER=$(DB-USER)
          DB_PASSWORD=$(DB-PASSWORD)
          SECRET_KEY=$(SECRET-KEY)
          EMAIL_HOST_PASSWORD=$(EMAIL-HOST-PASSWORD)
          PGADMIN_DEFAULT_PASSWORD=$(PGADMIN-DEFAULT-PASSWORD)

    - task: DockerCompose@0
      displayName: 'Push services'
      inputs:
        containerregistrytype: 'Azure Container Registry'
        azureSubscription: $(azureSubscription)
        azureContainerRegistry: $(containerRegistry)
        dockerComposeFile: $(composeFilePath)
        action: 'Push services'
        additionalImageTags: '$(Build.BuildId)'

- stage: Deploy
  displayName: Deploy to Azure Container Apps
  dependsOn: Build
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Install Container Apps Extension'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az extension add --name containerapp --upgrade
          az provider register --namespace Microsoft.App
          az provider register --namespace Microsoft.OperationalInsights

    - task: AzureCLI@2
      displayName: 'Deploy Container App'
      inputs:
        azureSubscription: $(azureSubscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Login to ACR
          az acr login --name $(containerRegistry)
          
          # Get the latest image tag
          WEB_IMAGE=$(az acr repository show-tags \
            --name $(containerRegistry) \
            --repository $(containerAppName) \
            --orderby time_desc \
            --query [0] -o tsv)
          
          # Create or update container app
          az containerapp update \
            --name $(containerAppName) \
            --resource-group $(resourceGroup) \
            --environment $(containerAppEnv) \
            --image $(containerRegistry)/$(containerAppName):$WEB_IMAGE \
            --target-port 8000 \
            --ingress external \
            --env-vars \
              DJANGO_SETTINGS_MODULE=$(DJANGO_SETTINGS_MODULE) \
              DB_HOST=$(DB-HOST) \
              DB_PORT=$(DB-PORT) \
              DB_NAME=$(DB-NAME) \
              DB_USER=$(DB-USER) \
              DEBUG=$(DEBUG) \
              ALLOWED_HOSTS=$(ALLOWED-HOSTS) \
              PGADMIN_DEFAULT_EMAIL=$(PGADMIN_DEFAULT_EMAIL) \
            --secrets \
              db-password=$(DB-PASSWORD) \
              secret-key=$(SECRET-KEY) \
              email-password=$(EMAIL-HOST-PASSWORD) \
              pgadmin-password=$(PGADMIN-DEFAULT-PASSWORD)

          # Show deployment status
          echo "Deployment completed. Application details:"
          az containerapp show \
            --name $(containerAppName) \
            --resource-group $(resourceGroup) \
            --query "{FQDN:configuration.ingress.fqdn,ProvisioningState:provisioningState,Revision:latestRevisionFqdn}" \
            -o table

          # Output the URL
          echo "##vso[task.setvariable variable=APP_URL]https://$(az containerapp show --name $(containerAppName) --resource-group $(resourceGroup) --query "configuration.ingress.fqdn" -o tsv)"