trigger:
- master

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: 'd932d5a2-7e91-48b9-b339-918c998b3ae9'
  containerRegistry: 'freshersparkregistry.azurecr.io'
  
  # Image repositories
  celeryImageRepository: 'freshersparkcelery'
  celeryDockerfilePath: '$(Build.SourcesDirectory)/Dockerfile.celery'
  
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

  # Environment configuration
  environmentType: 'dev'  # Set to 'prod' for production
  keyVaultName: 'freshersparkkeyvault'
  rabbitmqHost: 'freshersparkrabbitmq.internal'  # Added internal hostname

stages:
- stage: Build
  displayName: Build and push Celery image
  jobs:
  - job: BuildCelery
    displayName: Build Celery Image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push Celery image
      inputs:
        command: buildAndPush
        repository: $(celeryImageRepository)
        dockerfile: $(celeryDockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
        buildContext: '$(Build.SourcesDirectory)'

- stage: Deploy
  displayName: Deploy Celery Worker
  dependsOn: Build
  jobs:
  - job: DeployCelery
    displayName: Deploy Celery Worker
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: AzureCLI@2
      displayName: 'Configure Managed Identity'
      inputs:
        azureSubscription: '8ce37efe-06df-47c4-b146-001d3ddfb1ba'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Enable system-assigned identity
          echo "Assigning system identity..."
          az containerapp identity assign \
            --name freshersparkapp \
            --resource-group freshersparkresource \
            --system-assigned
          
          # Wait for propagation
          sleep 30
          
          # Get principal ID with error handling
          PRINCIPAL_ID=$(az containerapp identity show \
            --name freshersparkapp \
            --resource-group freshersparkresource \
            --query principalId -o tsv)
          
          if [ -z "$PRINCIPAL_ID" ]; then
            echo "##vso[task.logissue type=error]Failed to get principal ID"
            exit 1
          fi
          
          echo "Granting Key Vault access..."
          az keyvault set-policy \
            --name $(keyVaultName) \
            --object-id $PRINCIPAL_ID \
            --secret-permissions get list

    - task: AzureCLI@2
      displayName: 'Deploy Celery Worker'
      inputs:
        azureSubscription: '8ce37efe-06df-47c4-b146-001d3ddfb1ba'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          # Always use internal hostname
          BROKER_URL="amqp://$(secretref:rabbitmq-user):$(secretref:rabbitmq-pass)@$(rabbitmqHost):5672//"
          
          # Update container using YAML to avoid CLI issues
          echo "Updating Celery worker configuration..."
          az containerapp show \
            --name freshersparkapp \
            --resource-group freshersparkresource \
            --output yaml > config.yaml
          
          # Add/update environment variables
          yq e -i '(.properties.template.containers[] | select(.name == "celery-worker").env) += [
            {"name": "CELERY_BROKER_URL", "value": "'"$BROKER_URL"'"},
            {"name": "CELERY_RESULT_BACKEND", "value": "rpc://"},
            {"name": "DJANGO_SETTINGS_MODULE", "value": "job_portal.settings"}
          ]' config.yaml
          
          az containerapp update \
            --name freshersparkapp \
            --resource-group freshersparkresource \
            --yaml config.yaml
          
          # Scale settings
          az containerapp update \
            --name freshersparkapp \
            --resource-group freshersparkresource \
            --container-name celery-worker \
            --min-replicas 2 \
            --max-replicas 4
          
          # Restart to ensure changes take effect
          az containerapp restart \
            --name freshersparkapp \
            --resource-group freshersparkresource \
            --container-name celery-worker