version: '3.8'  # Update to a more recent version

services:
  django:
    build:
      context: ./  # Using relative path
      dockerfile: Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      DATABASE_URL: postgres://user:password@db:5432/mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  celery:
    build:
      context: ./  # Using relative path
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A your_project_name worker --loglevel=info
    depends_on:
      - rabbitmq
    volumes:
      - .:/app

  flower:
    image: mher/flower
    container_name: celery_flower
    command: celery -A your_project_name flower --port=5555
    depends_on:
      - rabbitmq
    ports:
      - "5555:5555"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3001"
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  pgdata:
  grafana-storage: