services:
  django:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: projectfresherspark_django
    command: bash -c "python manage.py makemigrations portal_admin_app && python manage.py makemigrations portal_user_app && python manage.py makemigrations portal_converter_app && python manage.py makemigrations portal_resume_app && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 job_portal.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: 'db'
      DB_PORT: ${DB_PORT}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
    networks:
      - my_network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - my_network

  celery:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A job_portal.celery worker --pool=solo -l info
    depends_on:
      - rabbitmq
    environment:
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
      CELERY_ACCEPT_CONTENT: 'application/json'
      CELERY_RESULT_SERIALIZER: 'json'
      CELERY_TASK_SERIALIZER: 'json'
      CELERY_TIMEZONE: 'Asia/Kolkata'
      CELERY_RESULT_BACKEND: 'rpc://'
    volumes:
      - .:/app
    networks:
      - my_network

  flower:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: celery_flower
    command: celery -A job_portal flower
    depends_on:
      - rabbitmq
    ports:
      - "5555:5555"
    environment:
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
      CELERY_ACCEPT_CONTENT: 'application/json'
      CELERY_RESULT_SERIALIZER: 'json'
      CELERY_TASK_SERIALIZER: 'json'
      CELERY_TIMEZONE: 'Asia/Kolkata'
      CELERY_RESULT_BACKEND: 'rpc://'
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  rabbitmqdata:

networks:
  my_network:
    driver: bridge