version: '3.8'

services:
  django:
    build:
      context: ./  # Assuming Django Dockerfile is at the root
      dockerfile: Dockerfile.django
    image: myacr.azurecr.io/django:latest  # ACR URL for the Django image
    container_name: django_app
    command: bash -c "python manage.py makemigrations portal_admin_app && python manage.py makemigrations portal_user_app && python manage.py makemigrations portal_converter_app && python manage.py makemigrations portal_resume_app && python manage.py migrate && python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 job_portal.wsgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - rabbitmq
    environment:
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DEBUG: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: 'db'
      DB_PORT: ${DB_PORT}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
    networks:
      - my_network

  db:
    build:
      context: ./postgres  # Directory where the PostgreSQL Dockerfile is located
      dockerfile: Dockerfile.postgres
    image: myacr.azurecr.io/postgres:latest  # ACR URL for PostgreSQL image
    container_name: postgres_db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - my_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8089:80"
    depends_on:
      - db
    networks:
      - my_network

  rabbitmq:
    build:
      context: ./rabbitmq  # Directory where the RabbitMQ Dockerfile is located
      dockerfile: Dockerfile.rabbitmq
    image: myacr.azurecr.io/rabbitmq:latest  # ACR URL for RabbitMQ image
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - my_network

  celery:
    build:
      context: ./  # Assuming Celery Dockerfile is at the root
      dockerfile: Dockerfile.celery
    image: myacr.azurecr.io/celery:latest  # ACR URL for Celery image
    container_name: celery_worker
    command: celery -A job_portal.celery worker --pool=solo -l info
    depends_on:
      - rabbitmq
    environment:
      SECRET_KEY: ${SECRET_KEY}
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
      CELERY_ACCEPT_CONTENT: 'application/json'
      CELERY_RESULT_SERIALIZER: 'json'
      CELERY_TASK_SERIALIZER: 'json'
      CELERY_TIMEZONE: 'Asia/Kolkata'
      CELERY_RESULT_BACKEND: 'rpc://'
    volumes:
      - .:/app
    networks:
      - my_network

  flower:
    build:
      context: ./  # Assuming Flower Dockerfile is at the root
      dockerfile: Dockerfile.flower
    image: myacr.azurecr.io/flower:latest  # ACR URL for Flower image
    container_name: celery_flower
    command: celery -A job_portal flower
    depends_on:
      - rabbitmq
    ports:
      - "5555:5555"
    environment:
      EMAIL_HOST_PASSWORD : ${EMAIL_HOST_PASSWORD}
      CELERY_BROKER_URL: 'amqp://guest:guest@rabbitmq//'
      CELERY_ACCEPT_CONTENT: 'application/json'
      CELERY_RESULT_SERIALIZER: 'json'
      CELERY_TASK_SERIALIZER: 'json'
      CELERY_TIMEZONE: 'Asia/Kolkata'
      CELERY_RESULT_BACKEND: 'rpc://'
    volumes:
      - .:/app
    networks:
      - my_network

volumes:
  pgdata:
  rabbitmqdata:

networks:
  my_network:
    driver: bridge
