# Base image
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django app files into the container
COPY . /app/

# Expose the necessary ports
EXPOSE 5555

# Run Flower
CMD celery -A job_portal flower
