FROM nginx:latest

# Create directory with correct permissions
RUN mkdir -p /apps/staticfiles && chown nginx:nginx /apps/staticfiles

# Copy config and static files
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --chown=nginx:nginx app/staticfiles/ /apps/staticfiles/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]